---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/blogs":
    post:
      summary: create blog
      responses:
        '200':
          description: successful
    get:
      summary: list blogs
      responses:
        '200':
          description: successful
  "/blogs/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show blog
      responses:
        '200':
          description: successful
    put:
      summary: update blog
      responses:
        '200':
          description: successful
    delete:
      summary: delete blog
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
